SummerCamp2017/SummerCamp2017/Models/AdvancedSearch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SummerCamp2017.Models
{
    public class AdvancedSearch
    {
        int? CategoryId { get; set; }
        string Title { get; set; }
        //DateTime? PostDate { get; set; }
        //DateTime? ExpirationDate { get; set; }

    }
}

SummerCamp2017/SummerCamp2017/Models/Announcement.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SummerCamp2017.Models
{
    public class Announcement
    {
        public int AnnouncementId { get; set; }
        public string Title { get; set; }
        public bool Closed { get; set; }
        public string CategoryName { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime PostDate { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime ExpirationDate { get; set; }
    }
}

SummerCamp2017/SummerCamp2017/Controllers/AnnouncementsController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using SummerCamp2017.Models;
using Plugin.RestClient;
using System.Net.Http;
using System.Net;
using Microsoft.Ajax.Utilities;
using System.Threading.Tasks;
using System.Net.Mail;
using System.Web.Services.Description;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web.Script.Serialization;
using Newtonsoft.Json;
using System.Security.Cryptography;
using System.Text;

namespace SummerCamp2017.Controllers
{
    public class AnnouncementsController : Controller
    {
        [HttpPost]
        [ValidateAntiForgeryToken]
        //public async Task<ActionResult> Create(AnnouncementPost model)
        //{
        //    SmtpClient client = new SmtpClient("some.server.com");
        //    //If you need to authenticate
        //    //client.Credentials = new NetworkCredential("username", "password");

        //    MailMessage mailMessage = new MailMessage();
        //    mailMessage.From = "andreea.mateiasi@yahoo.com";
        //    mailMessage.To.Add(model.Email);
        //    mailMessage.Subject = "Hello There";
        //    mailMessage.Body = "thank you for adding this announcement: " + model.Title;

        //    client.Send(mailMessage);

        //    return RedirectToAction("List");
        //}
        public ActionResult Index()
        {
            return View();
        }
        // GET: Announcements

        public List<Announcement> GetAnnouncements()
        {
            RestClient<Announcement> rc = new RestClient<Announcement>();
            rc.WebServiceUrl = "http://localhost:10469/api/announcements/";
            //rc.WebServiceUrl = "http://api.summercamp.stage02.netromsoftware.ro/api/announcements/";
            var announcementList = rc.GetAsync();
            return announcementList;
        }

        public List<Category> GetCategories()
        {
            RestClient<Category> rc = new RestClient<Category>();
            rc.WebServiceUrl = "http://localhost:10469/api/categories/";
            //rc.WebServiceUrl = "http://api.summercamp.stage02.netromsoftware.ro/api/categories";
            var categoryList = rc.GetAsync();
            return categoryList;
        }
        public List<Review> GetReviewsForAnnouncement(int id)
        {
            RestClient<Review> rc = new RestClient<Review>();
            rc.WebServiceUrl = "http://localhost:10469/api/reviews/GetByAnnouncementId?announcementId=" + id;
            //rc.WebServiceUrl = "http://api.summercamp.stage02.netromsoftware.ro/api/reviews/GetByAnnouncementId?announcementId=" + id;
            var reviewList = rc.GetAsync();
            return reviewList;
        }
        // POST: Announcement
        public HttpResponseMessage PostAnnouncement(AnnouncementPost a)
        {
            RestClient<AnnouncementPost> rc = new RestClient<AnnouncementPost>();
            rc.WebServiceUrl = "http://localhost:10469/api/Announcements/NewAnnouncement";
            //rc.WebServiceUrl = "http://api.summercamp.stage02.netromsoftware.ro/api/announcements/newannouncement";
            HttpResponseMessage response = rc.PostAsync(a);
            var id = response.Content.ReadAsStringAsync().Result;
            //string id = Request.Params["id"];
            //string type = Request.QueryString["id"];
            return response;
        }
        public AnnouncementReturn PostAnnouncementt(AnnouncementPost a)
        {
            RestClient<AnnouncementPost> rc = new RestClient<AnnouncementPost>();
            rc.WebServiceUrl = "http://localhost:10469/api/Announcements/NewAnnouncement";
            //rc.WebServiceUrl = "http://api.summercamp.stage02.netromsoftware.ro/api/announcements/newannouncement";
            HttpResponseMessage response = rc.PostAsync(a);
            var id = response.Content.ReadAsStringAsync().Result;
            //var c = JsonConvert.DeserializeObject<List<AnnouncementPost>>(id);
            AnnouncementReturn taskModels = JsonConvert.DeserializeObject<AnnouncementReturn>(id);
            //string c = JsonConvert.DeserializeObject<string>(id);

            return taskModels;
        }
        public AnnouncementDetails GetAnnouncementById(int id)
        {
            RestClient<AnnouncementDetails> rc = new RestClient<AnnouncementDetails>();
            rc.WebServiceUrl = "http://localhost:10469/api/announcements/"+id;

            //rc.WebServiceUrl = "http://api.summercamp.stage02.netromsoftware.ro/api/announcements/" + id;
            var announcement = rc.GetByIdAsyncc();
            return announcement;
        }
        public AnnouncementPost GetAnnouncementByIdw(int id)
        {
            RestClient<AnnouncementPost> rc = new RestClient<AnnouncementPost>();
            rc.WebServiceUrl = "http://localhost:10469/api/announcements/";
            //rc.WebServiceUrl = "http://api.summercamp.stage02.netromsoftware.ro/api/announcements/";

            var announcement = rc.GetByIdAsync(id);
            return announcement;
        }
        //public bool PutAnnouncement(int id, AnnouncementPost a)
        //{
        //    RestClient<AnnouncementPost> rc = new RestClient<AnnouncementPost>();
        //    rc.WebServiceUrl = "http://localhost:10469/api/announcements/PutAnnouncements";
        //    bool response = rc.PutAsync(id, a);
        //    return response;
        //}

        public HttpResponseMessage CloseAnnouncement(CloseAnnouncement email)
        {

            RestClient<AnnouncementDetails> rc = new RestClient<AnnouncementDetails>();
            rc.WebServiceUrl = "http://localhost:10469/api/Announcements/CloseAnnouncement/" + email.Id;
            //rc.WebServiceUrl = "http://api.summercamp.stage02.netromsoftware.ro/api/Announcements/CloseAnnouncement/" + email.Id;

            HttpResponseMessage response = rc.Close(email);

            return response;
        }
        public HttpResponseMessage ActivateAnn(CloseAnnouncement email)
        {
            RestClient<AnnouncementDetails> rc = new RestClient<AnnouncementDetails>();
             rc.WebServiceUrl = "http://localhost:10469/api/Announcements/ActivateAnnouncement/" + email.Id;
            //rc.WebServiceUrl = "http://api.summercamp.stage02.netromsoftware.ro/api/Announcements/ActivateAnnouncement/" + email.Id;

            HttpResponseMessage response = rc.Activate(email);

            return response;
        }

        //public HttpResponseMessage Search(AdvancedSearch model)
        //{
        //    RestClient<AdvancedSearch> rc = new RestClient<AdvancedSearch>();
        //    rc.WebServiceUrl = "http://localhost:10469/api/Announcements/ActivateAnnouncement/" + model.CategoryId;
        //    //rc.WebServiceUrl = "http://api.summercamp.stage02.netromsoftware.ro/api/Announcements/ActivateAnnouncement/" + email.Id;

        //    HttpResponseMessage response = rc.Search(model);

        //    return response;
        //}

        public HttpResponseMessage ExtendAnnouncement(CloseAnnouncement email)
        {

            RestClient<AnnouncementDetails> rc = new RestClient<AnnouncementDetails>();
            rc.WebServiceUrl = "http://localhost:10469/api/Announcements/ExtendAnnouncement/" + email.Id;
            //rc.WebServiceUrl = "http://api.summercamp.stage02.netromsoftware.ro/api/Announcements/ExtendAnnouncement/" + email.Id;

            HttpResponseMessage response = rc.Extend(email);

            return response;
        }
        public ActionResult Create()
        {
            List<Category> categoryList = GetCategories();
            ViewBag.data = categoryList;
            return View();
        }





        public ActionResult Edit(int id)
        {

            AnnouncementPost a = GetAnnouncementByIdw(id);

            return View(a);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AnnouncementPost a)
        {

            //PutAnnouncement(a.Id ,a);
            return RedirectToAction("List");
        }





        public string GenerateMD5(string yourString)
        {
            return string.Join("", MD5.Create().ComputeHash(Encoding.ASCII.GetBytes(yourString)).Select(s => s.ToString("x2")));
        }
        [HttpPost]
        public async Task<ActionResult> Create(AnnouncementPost model)
        {
            var a = PostAnnouncementt(model);
            string yourStringValue = a.AnnouncementId + a.Email;
            //var hashValue = string.Join("", MD5.Create().ComputeHash(Encoding.ASCII.GetBytes(yourStringValue)).Select(s => s.ToString("x2")));
            string hashed = GenerateMD5(yourStringValue);

            try
            {
                string body = "<a href='http://localhost:4116/announcements/ActivateAnnouncementEmail/?id=" + a.AnnouncementId + "&key=" + hashed + "'> confirm announcement</a>";
                var MailHelper = new MailHelper
                {
                    Sender = "mateiasiandreea19@gmail.com", //email.Sender,
                    Recipient = model.Email,
                    RecipientCC = null,
                    Subject = model.Title + " for sale",
                    Body = body
                };
                MailHelper.Send();

                
            }
            catch (Exception e)
            {
                ModelState.AddModelError("err", e);
                return View();
            }
            return RedirectToAction("List");
        }
        public ActionResult ActivateAnnouncementEmail(int id, string key)
        {
            CloseAnnouncement model = new CloseAnnouncement();
            AnnouncementDetails a = GetAnnouncementById(id);
            string concatenated = a.Id + a.Email;
            string hashed = GenerateMD5(concatenated);
            if(hashed == key)
            {
                model.Id = a.Id;
                model.Email = a.Email;
                HttpResponseMessage response = ActivateAnn(model);
                var s = response.StatusCode.ToString();

SummerCamp2017/SummerCamp2017/Views/Announcements/AdvancedSearch.cshtml
<style>
    label {
  display: inline-block;
  width: 140px;
  text-align: right;
}​
</style>
<br/>
<h1>Advanced search</h1>
<br/>
<div style="">
    <div class="dropdown" id="category">

        <label>Category:</label>
        <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" id="dropBttn">
            Select category
            <span class="caret"></span>
        </button>

        <ul class="dropdown-menu" id="dropDown" style="right:75%">

            @foreach (var item in (ViewBag.categories as List<SummerCamp2017.Models.Category>))
            {

                <li id="@item.CategoryId"><a href="#">@item.CategoryId - @item.Name</a></li>

            }

        </ul>


    </div>

    @*<div class="dropdown">
        <label>Categories</label>
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            Select
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1" style="right:75%">
            @foreach (var item in (ViewBag.categories as List<SummerCamp2017.Models.Category>))
            {

                <li id="@item.CategoryId"><a href="#">@item.CategoryId - @item.Name</a></li>

            }
        </ul>
    </div>*@

    <br />


    <script src="~/Scripts/jquery-1.10.2.min.js"></script>

    <div >
      
            <label>Title:</label> <input type="text" id="title" />

      
    </div>
    <br />
    <div>
        <label>Post Date:</label><input type="date" id="date1" />
    </div>
    <br/>
    <div>
        <label>Expiration Date:</label><input type="date" id="date2" />
    </div>

    @*<div class="container">
            <div class="row">
                <div class='col-sm-6'>
                    <div class="form-group">
                        <div class='input-group date' id='datetimepicker1'>
                            <input type='text' class="form-control" />
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                </div>
                <script type="text/javascript">
                    var initDatePicker = function () {
                        $('#datetimepicker1').datetimepicker();
                    };
                  window.onload = initDatePicker;
                </script>
            </div>
        </div>*@



    <button class="btn" id="searchButt" style="float:right; position: absolute; right: 60%;">
        Search
    </button>

</div>

<br/>
<br/>
<br/>   
<div class="container">
    <h2>Announcements</h2>
    <table class="table" id="tablet">
        <thead>
            <tr>
                <th>Title</th>
                <th>Description</th>
                <th>Start date</th>
                <th>End date</th>
                <th>Category</th>

            </tr>
        </thead>
        <tbody id="boddy">
            
        </tbody>
    </table>
</div>


<div id="divv"></div>

<div >
    <table id="tablet">
        <tr>
            

        </tr>
    </table>
</div>

<script>
    $(document).ready(function () {
        var id;
        $('#category').on("click", "li", function () {
            
            var string = this.innerText.trim();
            id = string.charAt(0);
            $(this).parents('#category').find('#dropBttn').html(string + '<span class="caret"></span>');
            //return dropDown;
        });
        $("#searchButt").on("click", function () {
            var CategoryId = id;
            //var CategoryId = 1;//$('#category').val();
            var Title = $('#title').val();
            var StartDate = $("#date1").val();
            var EndDate = $("#date2").val();

            if (Title === "") {
                Title = null;
            }
            debugger
            var obj = {

                'Text': Title,
                'StartDate': StartDate,
                'EndDate': EndDate

            };
            $.ajax({
                headers: {
                    'Accept': 'application/json',
                    'Content-Type': 'application/json'

                },
                type: 'POST',
                url: "http://localhost:10469/api/announcements/search/" + CategoryId,
                data: JSON.stringify(obj),
                crossOrigin: true,

                success: function (data) {
                    console.log(data);
                    $("#boddy tr").remove();
                    $("#divv p").remove();
                    if (data.length == 0) {
                        var elem = document.createElement("p");
                        var text = document.createTextNode("No announcement that maches your data was found!");
                        elem.appendChild(text);
                        var element = document.getElementById("divv");
                        element.appendChild(elem);
                    }
                    $.each((data), function () {
                        //$('#dropDownHome').append($("<li></li>").val(this['Destination']).html(this['Destination']));
                        // if (itemId == this.PackageId) {
                        console.log("got here");
                        console.log(this);
                        //<time datetime="1914-12-20">


                        var tr = document.createElement("tr");

                        var td1 = document.createElement("th");
                        var td2 = document.createElement("th");
                        var td3 = document.createElement("th");
                        var td4 = document.createElement("th");
                        var td5 = document.createElement("th");


//                        var time = document.createElement("time");
  //                      time.setAttribute("datetime", this.StartDate);
                        

                        var date1 = "date: "+this.EndDate.substr(0, 4) + "-" + this.EndDate.substr(5, 2) + "-"
                            + this.EndDate.substr(8, 2) + " time: " + this.EndDate.substr(11, 2) + ":" + this.EndDate.substr(14, 2);
                        var date2 = "date: " + this.StartDate.substr(0, 4) + "-" + this.StartDate.substr(5, 2) + "-"
                            + this.StartDate.substr(8, 2) + " time: " + this.StartDate.substr(11, 2) + ":" + this.StartDate.substr(14, 2);

                        var plane = document.createTextNode(this.Title);
                        var a = document.createTextNode(this.CategoryName);
                        var b = document.createTextNode(date2);
                        var c = document.createTextNode(date1);
                        var d = document.createTextNode(this.Description);

                        td1.appendChild(plane);
                        td2.appendChild(d);
                        td3.appendChild(b);
                        td4.appendChild(c);
                        td5.appendChild(a);

                        tr.appendChild(td1);
                        tr.appendChild(td2);
                        tr.appendChild(td3);
                        tr.appendChild(td4);
                        tr.appendChild(td5);

                        var element = document.getElementById("boddy");
                        element.appendChild(tr);
                        //li_dropdown_home
                        // }
                    });


                },
                error: function (response) {
                    console.log('error updating user by admin');
                    console.log(response);
                }
            })
        });
        //});


    });
    
    //$(document).ready(function () {
    
</script>

SummerCamp2017/SummerCamp2017/Views/Announcements/Close.cshtml
@model SummerCamp2017.Models.CloseAnnouncement
 

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Id)

    <div class="form-group">
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email)
           
            @Html.ValidationMessage("err")
        </div>
    </div>
    <button type="submit">Close annuncement</button>
}

@Html.ActionLink("Back to announcements list", "List")

SummerCamp2017/SummerCamp2017/Views/Announcements/Create.cshtml
@model SummerCamp2017.Models.AnnouncementPost

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Create Announcement </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.CategoryId, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })*@

                @Html.DropDownListFor(model => model.CategoryId, new SelectList(ViewBag.data, "CategoryId", "Name"))
             
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phonenumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phonenumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phonenumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
}

SummerCamp2017/SummerCamp2017/Views/Announcements/Edit.cshtml
@model SummerCamp2017.Models.AnnouncementDetails

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Announcement Edit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phonenumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phonenumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phonenumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpirationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpirationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpirationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Closed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Closed)
                    @Html.ValidationMessageFor(model => model.Closed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "List")
</div>

SummerCamp2017/SummerCamp2017/Views/Announcements/Extend.cshtml
@model SummerCamp2017.Models.CloseAnnouncement


@using (Html.BeginForm("Extend", "Announcements", null, FormMethod.Post))
{
    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Id)

    <div class="form-group">
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email)
            @Html.ValidationMessage("err")
        </div>
    </div>
    <button id="submitBttn" type="submit">Extend announcement</button>
}

@Html.ActionLink("Back to announcements list", "List" )